language: csharp
dotnet: 2.1.401
os: linux
mono: none
dist: trusty
env:
 global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
 - dotnet restore
 - dotnet build
 - cd test/Tars.Net.UT
 - dotnet minicover instrument --workdir ../../ --assemblies test/**/bin/**/*.dll --sources src/**/*.cs 
 - dotnet minicover reset
 - cd ../../
 - for project in test/**/*.csproj; do dotnet test --no-build $project; done
 - cd test/Tars.Net.UT
 - dotnet minicover uninstrument --workdir ../../
 - dotnet minicover htmlreport --workdir ../../ --threshold 10
 - dotnet minicover report --workdir ../../ --threshold 10

deploy:
 - provider: script
   script: 
    - export Version=$(cat version)-beta-$(date +%Y%m%d%H%M%S)
    - dotnet pack -c Release --output $PWD/artifacts/ci
    - dotnet nuget push artifacts/release/*.nupkg -k $NUGET_KEY -s https://api.nuget.org/v3/index.json
   on:
    branch: develop
 - provider: script
   script: chmod +x ./deploy-tag.sh && ./deploy-tag.sh
   on:
    tags: true