language: csharp
dotnet: 2.1.401
os: linux
mono: none
dist: trusty
env:
 global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
 - dotnet restore
 - dotnet build
 - cd test/Tars.Net.UT
 - dotnet minicover instrument --workdir ../../ --assemblies test/**/bin/**/*.dll --sources src/**/*.cs 
 - dotnet minicover reset
 - cd ../../
 - for project in test/**/*.csproj; do dotnet test --no-build $project; done
 - cd test/Tars.Net.UT
 - dotnet minicover uninstrument --workdir ../../
 - dotnet minicover htmlreport --workdir ../../ --threshold 10
 - dotnet minicover report --workdir ../../ --threshold 10

deploy:
 - provider: script
   script: ./deploy-branch.sh
   on:
    branch: develop
 - provider: script
   script: ./deploy-tag.sh
   on:
    tags: true